# Generated by Django 4.1 on 2022-08-29 11:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Star',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poster', models.FileField(blank=True, null=True, upload_to='series/')),
                ('name', models.CharField(max_length=200)),
                ('writer', models.CharField(max_length=200)),
                ('director', models.CharField(max_length=200)),
                ('distribution', models.CharField(max_length=200)),
                ('release', models.DateField(max_length=200)),
                ('summary', models.TextField(max_length=2000, null=True)),
                ('categorie', models.ManyToManyField(null=True, to='main.categorie')),
                ('star', models.ManyToManyField(null=True, to='main.star')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poster', models.FileField(blank=True, null=True, upload_to='movies/')),
                ('name', models.CharField(max_length=200)),
                ('writer', models.CharField(max_length=200)),
                ('director', models.CharField(max_length=200)),
                ('distribution', models.CharField(max_length=200)),
                ('release', models.DateField(max_length=200)),
                ('summary', models.TextField(max_length=2000, null=True)),
                ('categorie', models.ManyToManyField(null=True, to='main.categorie')),
                ('star', models.ManyToManyField(null=True, to='main.star')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
