# Generated by Django 4.1 on 2022-08-29 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_series_categorie_alter_series_star'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='categorie',
            field=models.ManyToManyField(blank=True, null=True, to='main.categorie'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='star',
            field=models.ManyToManyField(blank=True, null=True, to='main.star'),
        ),
    ]
