# Generated by Django 4.1 on 2022-08-30 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_movie_categorie_alter_movie_star'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='category',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='star',
            name='star_name',
            field=models.CharField(max_length=500),
        ),
    ]
