# Generated by Django 4.1 on 2022-08-30 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_categorie_category_alter_star_star_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='url_name',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
