# Generated by Django 4.1 on 2022-09-02 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_movie_url_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='categorie',
            field=models.ManyToManyField(blank=True, to='main.categorie'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='star',
            field=models.ManyToManyField(blank=True, to='main.star'),
        ),
        migrations.AlterField(
            model_name='series',
            name='categorie',
            field=models.ManyToManyField(blank=True, to='main.categorie'),
        ),
        migrations.AlterField(
            model_name='series',
            name='star',
            field=models.ManyToManyField(blank=True, to='main.star'),
        ),
    ]
